dd <number_small>: user.desktop(number_small)
dd next: user.desktop_next()
dd last: user.desktop_last()
dd show: user.desktop_show()
window move desk <number>: user.window_move_desktop(number)
window move desk left: user.window_move_desktop_left()
window move desk right: user.window_move_desktop_right()
